name: chem563
channels:
  - conda-forge
  - pyviz
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - plotly
  - bokeh
  - holoviz
  - scipy
  - pip
  - ipydatawidgets
  - ipykernel
  - pip:
    - matplotlib-venn
